### ISSUE TITLE
[BUG] Wrong tracks number on the visual library dropdown

### ISSUE THREAD

**Issue by werdeil** [AF-1/lms-dynamicplaylistcreator#2]
**Please a look at the *closed* issues first to avoid duplicates. Thank you.**

**Describe the bug**
This bug is the same you had on the Visual Statistics plugin: the virtual library dropdown when editing/creating a playlist is showing the thousand not the number

<img width="506" alt="Capture d’écran 2022-11-16 à 15 13 41" src="https://user-images.githubusercontent.com/6229844/202205003-3d94a40f-b2cd-439f-845f-bf549afb8df0.png">

**To Reproduce**
1. In a FR setting, create a new playlist (I choose the "Random Tracks Advanced" but I guess it is the same elsewhere.
2. Click on `Always limit to this virtual library` dropdown
3. See error (see screenshot)

**Expected behavior**
The correct number of tracks of each virtual libraries

**DPLC template info - REQUIRED**
Add the (contents of the) “.sql“ and “.customvalues.xml“ files (from the DPLC folder) that belong to the dynamic playlist you've created.

None as this happens before creating a playlist

**Log excerpt**
N/A

**Version info**
LMS version: 8.3.0 - 1667251155
OS (version): Ubuntu 20.04
Plugin version: 0.1.1
Web skin/controller:  LMS Default and Material
Browser (version): Safari 16.1 

**Screenshots**
See above

**Comment by AF-1** [comment]
Can you confirm 0.1.2 fixed the issue before I close this? Thanks.

**Comment by werdeil** [comment]
I just tested on 0.1.2 and the issue seems to be still there.

**Comment by werdeil** [comment]
I just tested on 0.2.1 and it is fixed now 👍
