### ISSUE TITLE
[BUG] Playlist added to the wrong player

### ISSUE THREAD

**Issue by werdeil** [AF-1/lms-dynamicplaylistcreator#3]
**Please a look at the *closed* issues first to avoid duplicates. Thank you.**

**Describe the bug**
I came accross a strange behavior and I can't understand why a create DPL can work like this: When adding tracks to a player the tracks are added to another one.

**To Reproduce**
0. Have an installation with at least 2 players and have a define playlist (see attached one)
1. Select the second player of the list
2. Click on add tracks to the playlist button
3. The display switch back to the other player and add tracks to it.

**Expected behavior**
I would expect to add tracks to the currently selected player.

**DPLC template info - REQUIRED**
```
-- PlaylistName:Random Tracks - Advanced Test Vincent
-- PlaylistGroups:Dynamic Playlist Creator
-- PlaylistCategory:songs
-- BaseTemplate:Random Tracks - Advanced
-- Scope:dplonly
-- PlaylistLimitOption:15
select distinct tracks.url from tracks
	left join tracks_persistent on
		tracks.url = tracks_persistent.url
	join alternativeplaycount on
		alternativeplaycount.urlmd5 = tracks.urlmd5
	left join dynamicplaylist_history on
		tracks.id = dynamicplaylist_history.id and dynamicplaylist_history.client = 'PlaylistPlayer'
	WHERE
		tracks.audio = 1
		and dynamicplaylist_history.id is null
		and tracks.secs > 30
		and tracks.content_type in ('alc')
		and ifnull(alternativeplaycount.playCount,0) = 0
	order by random()
	limit 15;
```

```
<?xml version="1.0" encoding="utf-8"?>
<dynamicplaylistcreator>
	<template>
		<id>randomtracks_advanced.sql.xml</id>
		<parameter type="text" id="playlistname"><value>Random Tracks - Advanced Test Vincent</value></parameter>
		<parameter type="text" id="playlistgroups"><value>Dynamic Playlist Creator</value></parameter>
		<parameter type="text" id="request1fromuser"></parameter>
		<parameter type="text" id="request2fromuser"></parameter>
		<parameter type="text" id="notrepeat"><value>1</value></parameter>
		<parameter type="text" id="minlength"><value>30</value></parameter>
		<parameter type="text" id="maxlength"></parameter>
		<parameter type="text" id="minyear"></parameter>
		<parameter type="text" id="maxyear"></parameter>
		<parameter type="text" id="playedbefore"><value>1</value></parameter>
		<parameter type="text" id="recentlyplayed"></parameter>
		<parameter type="text" id="useapcvalues"><value>1</value></parameter>
		<parameter type="text" id="maxskipcount"></parameter>
		<parameter type="text" id="recentlyskipped"></parameter>
		<parameter type="text" id="includedcomment" quotevalue="1"></parameter>
		<parameter type="text" id="excludedcomment" quotevalue="1"></parameter>
		<parameter type="text" id="minrating"></parameter>
		<parameter type="text" id="exactrating"></parameter>
		<parameter type="text" id="minbitrate"></parameter>
		<parameter type="text" id="maxbitrate"></parameter>
		<parameter type="text" id="minsamplerate"></parameter>
		<parameter type="text" id="maxsamplerate"></parameter>
		<parameter type="text" id="minbpm"></parameter>
		<parameter type="text" id="maxbpm"></parameter>
		<parameter type="text" id="lyrics"><value>0</value></parameter>
		<parameter type="text" id="includedgenres" quotevalue="1"></parameter>
		<parameter type="text" id="excludedgenres" quotevalue="1"></parameter>
		<parameter type="text" id="includedartists" quotevalue="1"></parameter>
		<parameter type="text" id="excludedartists" quotevalue="1"></parameter>
		<parameter type="text" id="lossless"><value>0</value></parameter>
		<parameter type="text" id="includedcontenttypes" quotevalue="1"><value>alc</value></parameter>
		<parameter type="text" id="orderbyplaycount"></parameter>
		<parameter type="text" id="remote"></parameter>
		<parameter type="text" id="nooftracks"><value>15</value></parameter>
		<parameter type="text" id="activevirtuallibrary"><value>0</value></parameter>
		<parameter type="text" id="virtuallibrary"></parameter>
	</template>
</
````

**Log excerpt**
Add relevant (error) messages from the LMS server log.
N/A

**Version info**
LMS version: 8.3.0 - 1667251155
OS (version): Ubuntu 20.04
Plugin version: 0.1.1
Web skin/controller:  Examples: LMS Default (Issue is not present on Material view)
Browser (version): Safari 16.1

**Screenshots**
See video shared on wetransfer

**Additional context**

**Uploads**
https://we.tl/t-cG8Tx4R3hX

**Comment by AF-1** [comment]
I deal with this bug on a regular basis. I'd say it's a _Default skin_ bug, therefore not present in Material or on jivelite controllers. The DPL code to add tracks to a client's playlist is the same for all 3. But they get the client ID (= player to add tracks to) from the skin.
I have one player connected to LMS at all times. It happens when I power up another player and sometimes when I restart LMS.
I doesn't matter what you use to add tracks to the client playlist (DPL or manual adding), as long as Default skin provides the wrong client ID they get added to the wrong client.
My workaround: select the correct player top right and reload the page 2-3 times in your browser.

**Comment by AF-1** [comment]
@werdeil I've uploaded DPL **4** and DPLC **0.3.0** to GitHub. 
I'd appreciate it if you could take a look at a few new FR strings in DPL 4. I think I've marked most of them with ???

Maybe you can switch to DPL**4** if you test DPLC 0.3.0. I wrote a short (upgrade) DPL FAQ paragraph with details, relevant if you have created **custom** dynamic playlists (with or without DPLC).
