### ISSUE TITLE
[BUG] Dynamic Playlist Creator folder not as the other one in the Default skin

### ISSUE THREAD

**Issue by werdeil** [AF-1/lms-dynamicplaylistcreator#4]
**Please a look at the *closed* issues first to avoid duplicates. Thank you.**

**Describe the bug**
In the default skin the DPLC folder is not bold as the other folder, I don't see a reason to make it differ from the other. On Material skin it is as the others.

**To Reproduce**
1. Go to the DPL view on a default skin
2. The DPLC folder is not displayed as the others

**Expected behavior**
Have all folder displayed the same way.

**DPLC template info - REQUIRED**
N/A

**Log excerpt**
N/A

**Version info**
LMS version: 8.3.0 - 1667251155
OS (version): Ubuntu 20.04
Plugin version: 0.1.1
Web skin/controller:  LMS Default
Browser: Safari 16.1

**Screenshots**
<img width="315" alt="Capture d’écran 2022-11-16 à 15 14 16" src="https://user-images.githubusercontent.com/6229844/202210230-e6e57337-c16d-420a-b919-ab0d3325f45a.png">

**Comment by AF-1** [comment]
That's actually not a bug but by design. Bold playlist group names cannot be changed by users, only hidden/disabled. 
_Dynamic Playlist Creator_ is just the default value in DPLC templates for DPL playlist group names so DPLC playlists are easier to find. It can be changed to whatever and is therefore not bold.

**Comment by werdeil** [comment]
Ok if it is intended. Even if I find it strange and as it Is not the case on other skins.
This is the kind of UI/UX choice that I would have differently but I'm not the developer and I can accommodate without issue.
