### ISSUE TITLE
[ISSUE] Unable to save playlist (no custom dir configured) 

### ISSUE THREAD

**Issue by samuraibrian** [AF-1/lms-dynamicplaylistcreator#5]
**Please read the *FAQ* (if available) and take a look at the *closed* issues first to avoid duplicates. Thank you.**

---

## DESCRIBE THE BUG

<br><br>
## TO REPRODUCE
1. Go to 'final playlist configuration screen'
2. Click on 'Save'
4. See error Error: no custom dir configured

<br><br>
## EXPECTED BEHAVIOR
Custom playlist to be saved

<br><br>
## LOG EXCERPT
* Add relevant (error) messages from the **LMS server log** (file path at the bottom of *LMS settings* > *Information*). Use the **time stamps** in the log to find messages created around the time your problem occurred.
* If there are no server log error messages, set the **debug level for this plugin** to **info** in *LMS settings* > *Advanced* > *Logging*, **reproduce the problem** and **check the server log** again. If there's still nothing, **repeat** this step with the debug level set to **debug**.
* Alternatively, *upload the complete LMS server log file somewhere* (see UPLOADS below) and don't forget to *add the time stamp of when the problem occurred*.
[23-05-16 16:06:06.5623] Plugins::DynamicPlaylistCreator::Plugin::__ANON__ (84) Could not create or access dynamic playlists folder in parent folder '/media/music-drive/customplaylists'!
[23-05-16 16:06:32.0116] Plugins::DynamicPlaylists4::Plugin::__ANON__ (215) Could not create or access custom playlist folder in parent folder '/media/music-drive/customplaylists'!
[23-05-16 16:06:59.1820] Slim::Utils::Misc::msg (1321) Warning: [16:06:59.1809] Use of uninitialized value in subroutine entry at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/DynamicPlaylistCreator/ConfigManager/WebPageMethods.pm line 457.
[23-05-16 16:06:59.1830] Slim::Utils::Misc::msg (1321) Warning: [16:06:59.1824] Use of uninitialized value in subroutine entry at /var/lib/squeezeboxserver/cache/InstalledPlugins/Plugins/DynamicPlaylistCreator/ConfigManager/WebPageMethods.pm line 458.

<br><br>
## DYNAMIC PLAYLIST INFO
If the issue involves a **dynamic playlist** created with *DPLC*, please provide
the **contents of the “.sql“ and “.customvalues.xml“ files** (from the DPLC folder) that belong to the dynamic playlist you've created.

<br><br>
## VERSION INFO
* LMS version: 8.4.0 - 1680780553 @ Thu 06 Apr 2023 01:59:09 PM CEST
* OS (version):
*  Server: Debian Linux lms1 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
* Client: Manjaro Linux jon-t570 6.2.13-1-MANJARO #1 SMP PREEMPT_DYNAMIC Wed Apr 26 21:52:27 UTC 2023 x86_64 GNU/Linux
* Plugin version: DPLC v1.2.4, DP v4.1.4
* Web skin/controller:     LMS Default
* Browser (version): Firefox 113.0 (64-bit)
If the problem occurs with a specific web skin/controller (e.g. Material), please check whether it also occurs when using other web skins/controllers (e.g. LMS default skin).

<br><br>
## SCREENSHOTS

<br><br>
## ADDITIONAL CONTEXT
I have configured both DPLC & DP in LMS Advanced Plugins webpage. Neither would accept a folder that I had specifically created (/media/music-drive/customplaylists) - both would only seem to accept my LMS Playlists folder /media/music-drive/Playlists (which both plugins were pre-filled with).

<br><br>
## UPLOADS
In case you want to provide larger files to illustrate the problem (e.g. your library.db, persist.db or LMS server log file), please use a service like **https://wetransfer.com/** and **include the download link in your bug report**.
<br>

**Comment by AF-1** [comment]
Thanks for using the GH issue template.

Whenever LMS is (re)started, DPLC checks if there's a folder called "DynamicPlaylistCreator" in the parent folder you can set in DPLC's preferences (the DPLC folder **name** is hard-coded though). That's where DPLC stores all files related to your custom dynamic playlists and where the _Dynamic Playlists_ plugin looks for DPLC' custom dynamic playlists.
If it doesn't find the folder "DynamicPlaylistCreator" inside the parent folder, it will try to create it.

Looking at the server log messages, this could be a permissions problem, i.e. DPLC can't create the folder / has no write permissions for the parent folder (or the "DynamicPlaylistCreator" folder).
Please make sure that LMS has r/w permissions (755) for the parent folder where DPLC creates the "DynamicPlaylistCreator" folder. If in doubt, set the correct permissions for the parent folder, delete the "DynamicPlaylistCreator" (if it's empty) and restart LMS have DPLC auto-create the "DynamicPlaylistCreator" folder.
I hope this solves the problem. Let me know.

**Comment by samuraibrian** [comment]
Thanks AF-1. Thought it was likely to be permissions! All sorted now.

Kind Regards, Jon

**Comment by samuraibrian** [comment]
Just a thought, bearing in mind the error message in the plugin config
screen is a bit 'generic' - maybe add a 'Permissions for numpties' item to
the FAQ 😃 (I've been a Linux user for 20+ years, even done a bit of server
admin, professionally...)
